#!/usr/bin/env bash
# ponytail: no daemon/supervisor. Each background job is a detached `agy`
# subshell that drops a .done marker when it exits; status/result/cancel
# just reconcile against that marker (or the pid) whenever they're queried.
set -uo pipefail

# Job/state files may land in a shared temp dir if CLAUDE_PLUGIN_DATA isn't
# set, so keep them from being world-readable regardless of the caller's
# umask.
umask 077

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

job_root() {
  local dir
  dir="$("$SCRIPT_DIR/resolve-state-dir.sh")/jobs"
  mkdir -p "$dir"
  printf '%s\n' "$dir"
}

now() { date -u +%Y-%m-%dT%H:%M:%SZ; }

# Job/done files are plain `key=value` lines, one value per line — never
# shell-sourced. Values must not contain newlines (stripped on write) so
# each line stays exactly one field; no quoting/escaping is needed since we
# only ever split on the first `=`, never evaluate the value as shell.
oneline() { printf '%s' "$1" | tr '\n\r' '  '; }

write_job_file() {
  local file="$1"
  {
    printf 'id=%s\n' "$id"
    printf 'status=%s\n' "$status"
    printf 'pid=%s\n' "${pid:-}"
    printf 'model=%s\n' "$(oneline "${model:-}")"
    printf 'mode=%s\n' "${mode:-}"
    printf 'write=%s\n' "${write:-0}"
    printf 'created_at=%s\n' "${created_at:-}"
    printf 'completed_at=%s\n' "${completed_at:-}"
    printf 'exit_code=%s\n' "${exit_code:-}"
    printf 'out_file=%s\n' "${out_file:-}"
    printf 'summary=%s\n' "$(oneline "${summary:-}")"
    printf 'conversation_id=%s\n' "${conversation_id:-}"
  } > "$file"
}

# Reads a job/.done file without ever sourcing/evaling it: split each line
# on the first `=` and only assign known field names. This is deliberately
# not `. "$file"` — that would execute arbitrary shell code if a job file
# ever ended up attacker-controlled (e.g. a shared, world-writable temp
# dir), and would let any key (not just our known fields) set arbitrary
# shell variables like PATH or IFS.
read_job_file() {
  local file="$1" line key value
  while IFS= read -r line || [ -n "$line" ]; do
    [ -n "$line" ] || continue
    key="${line%%=*}"
    value="${line#*=}"
    case "$key" in
      id|status|pid|model|mode|write|created_at|completed_at|exit_code|out_file|summary|conversation_id)
        printf -v "$key" '%s' "$value"
        ;;
      *) : ;;
    esac
  done < "$file"
}

# Job ids are only ever generated by cmd_start below, but status/result/
# cancel also accept one from the caller (a slash command's $ARGUMENTS) —
# validate it before it touches a file path, so a crafted id can't escape
# the jobs directory (e.g. "../../etc/passwd").
valid_job_id() {
  case "$1" in
    ''|*[!A-Za-z0-9_-]*) return 1 ;;
    *) return 0 ;;
  esac
}

reconcile() {
  local job_file="$1"
  id= status= pid= model= mode= write= created_at= completed_at= exit_code= out_file= summary= conversation_id=
  read_job_file "$job_file"
  if [ "$status" = "running" ]; then
    local done_file="${job_file%.job}.done"
    if [ -f "$done_file" ]; then
      exit_code= completed_at= conversation_id=
      read_job_file "$done_file"
      if [ "$exit_code" = "0" ]; then status=completed; else status=failed; fi
      pid=
      write_job_file "$job_file"
    elif [ -n "$pid" ] && ! kill -0 "$pid" 2>/dev/null; then
      status=failed
      completed_at="$(now)"
      pid=
      write_job_file "$job_file"
    fi
  fi
}

cmd_start() {
  local model="" mode="task" write=0 add_dir="" prompt_file="" summary=""
  while [ $# -gt 0 ]; do
    case "$1" in
      --model) model="$2"; shift 2 ;;
      --mode) mode="$2"; shift 2 ;;
      --write) write=1; shift ;;
      --add-dir) add_dir="$2"; shift 2 ;;
      --prompt-file) prompt_file="$2"; shift 2 ;;
      --summary) summary="$2"; shift 2 ;;
      *) echo "start: unknown arg $1" >&2; exit 2 ;;
    esac
  done
  [ -n "$model" ] || { echo "start: --model is required" >&2; exit 2; }
  [ -n "$prompt_file" ] && [ -f "$prompt_file" ] || { echo "start: --prompt-file must exist" >&2; exit 2; }

  local dir; dir="$(job_root)"
  id="gemini-$(date -u +%Y%m%d-%H%M%S)-$$"
  out_file="$dir/$id.out"
  local done_file="$dir/$id.done"
  local job_file="$dir/$id.job"
  : > "$out_file"

  local agy_args=(-p --model "$model")
  if [ "$write" = "1" ]; then
    agy_args+=(--dangerously-skip-permissions --sandbox)
    [ -n "$add_dir" ] && agy_args+=(--add-dir "$add_dir")
  fi

  local start_cwd="$PWD"
  (
    umask 077
    agy "${agy_args[@]}" < "$prompt_file" > "$out_file" 2>&1
    rc=$?
    conv_id="$("$SCRIPT_DIR/gemini-conversation-id.sh" "$start_cwd" 2>/dev/null || true)"
    {
      printf 'exit_code=%s\n' "$rc"
      printf 'completed_at=%s\n' "$(now)"
      printf 'conversation_id=%s\n' "$(oneline "$conv_id")"
    } > "$done_file"
  ) &
  pid=$!
  disown 2>/dev/null || true

  status=running
  created_at="$(now)"
  completed_at=
  exit_code=
  write_job_file "$job_file"

  echo "$id"
}

cmd_status() {
  local dir; dir="$(job_root)"
  if [ $# -ge 1 ] && [ -n "$1" ]; then
    valid_job_id "$1" || { echo "invalid job id: $1" >&2; exit 2; }
    local job_file="$dir/$1.job"
    [ -f "$job_file" ] || { echo "no such job: $1" >&2; exit 1; }
    reconcile "$job_file"
    printf 'id: %s\nstatus: %s\nmode: %s\nwrite: %s\nmodel: %s\ncreated_at: %s\ncompleted_at: %s\nexit_code: %s\nsummary: %s\nout_file: %s\n' \
      "$id" "$status" "$mode" "$write" "$model" "$created_at" "${completed_at:-}" "${exit_code:-}" "$summary" "$out_file"
    if [ -n "${conversation_id:-}" ]; then
      printf 'continue in Antigravity CLI: agy --conversation %s\n' "$conversation_id"
    fi
    return
  fi

  local f found=0
  for f in "$dir"/*.job; do
    [ -e "$f" ] || break
    found=1
    reconcile "$f"
    printf '%s\t%s\t%s\t%s\t%s\n' "$id" "$status" "$mode" "$created_at" "$summary"
  done | sort -t "$(printf '\t')" -k4 -r
  [ "$found" = "1" ] || echo "no gemini jobs yet"
}

cmd_result() {
  local dir; dir="$(job_root)"
  local job_id="${1:-}"
  if [ -z "$job_id" ]; then
    local latest
    latest="$(ls -t "$dir"/*.job 2>/dev/null | head -1)"
    [ -n "$latest" ] || { echo "no gemini jobs yet" >&2; exit 1; }
    job_id="$(basename "$latest" .job)"
  else
    valid_job_id "$job_id" || { echo "invalid job id: $job_id" >&2; exit 2; }
  fi
  local job_file="$dir/$job_id.job"
  [ -f "$job_file" ] || { echo "no such job: $job_id" >&2; exit 1; }
  reconcile "$job_file"
  echo "job: $id  status: $status  model: $model"
  echo "---"
  cat "$out_file"
  if [ -n "${conversation_id:-}" ]; then
    echo "---"
    echo "continue in Antigravity CLI: agy --conversation $conversation_id"
  fi
}

cmd_cancel() {
  local dir; dir="$(job_root)"
  local job_id="${1:-}"
  [ -n "$job_id" ] || { echo "cancel: job id required" >&2; exit 2; }
  valid_job_id "$job_id" || { echo "invalid job id: $job_id" >&2; exit 2; }
  local job_file="$dir/$job_id.job"
  [ -f "$job_file" ] || { echo "no such job: $job_id" >&2; exit 1; }
  reconcile "$job_file"
  case "${pid:-}" in
    ''|*[!0-9]*) pid= ;;
  esac
  if [ "$status" != "running" ] || [ -z "$pid" ]; then
    echo "job $job_id is not running (status: $status)"
    return
  fi
  # pid is validated all-digits above — a stray/tampered non-numeric value
  # (e.g. "-1") must never reach kill/pkill, which would target far more
  # than this one job's process.
  pkill -P "$pid" 2>/dev/null || true
  kill "$pid" 2>/dev/null || true
  status=cancelled
  completed_at="$(now)"
  pid=
  write_job_file "$job_file"
  echo "cancelled $job_id"
}

cmd="${1:-}"
[ $# -gt 0 ] && shift
case "$cmd" in
  start) cmd_start "$@" ;;
  status) cmd_status "$@" ;;
  result) cmd_result "$@" ;;
  cancel) cmd_cancel "$@" ;;
  *) echo "usage: gemini-jobs.sh start|status|result|cancel ..." >&2; exit 2 ;;
esac
